### ISSUE TITLE
[readme typos] Potential typos in the readme.md file

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/aop#109]
**Describe the bug**
In the [AoP readme](https://github.com/streamnative/aop), there are some potential typos.
1. Should it be "Plugin" or "PluginF" for this [title](https://github.com/streamnative/aop#config-pulsar-broker-to-run-aop-protocol-handler-as-pluginf)?
![image](https://user-images.githubusercontent.com/47805623/84640475-4ccac380-af2c-11ea-8faf-6af8b50d42e4.png)
2. Remove period at the end of headings/titles
![image](https://user-images.githubusercontent.com/47805623/84640601-7d126200-af2c-11ea-9e32-284f9cf43bf8.png)

**Comment by Jennifer88huang** [comment]
Huanli shares a. link: https://streamnative.io/docs/latest/connect/aop/limitation

**Comment by Jennifer88huang** [comment]
https://github.com/streamnative/aop/pull/135

**Comment by Jennifer88huang** [comment]
@sijia-w could you please help refine this readme when Ran gives feedback? Thank you.

**Comment by sijia-w** [comment]
@Jennifer88huang  OK. Will do.
