### ISSUE TITLE
aop开发功能点梳理

### ISSUE THREAD

**Issue by wangshaojie4039** [streamnative/aop#2]
## 协议层相关的开发

1. 协议版本解析和校验
2. 编解码
3. 序列化和发序列化
4. connection和channel处理

## vhost相关的开发

1. vhost增删改查接口开发
2. vhost和namespace的转换

## exchange开发

1. exchange的增删改查接口
2. exchange和pulsar中exchange-topic的映射转换
3. exchange不同类型的路由规则的实现
4. exchange-topic的消息存储实现
5. exchange-topic索引分发逻辑实现
6. exchange-topic的ack机制实现
7. 备份交换器实现
8. queue和exchange绑定逻辑的实现
9. exchange和exchange的绑定

## queue开发

1. queue相关增删改查接口
2. queue和pulsar中queue-topic的映射和转换
3. queue-topic中索引存储的实现
4. 消息过期ttl的实现
5. 队列exclusive排他实现
6. 死信队列的实现
7. 队列优先级的实现
8. 延迟队列的实现

## 消息发送流程

1. 发送端的ack机制实现
2. 发送的事务txn实现
3. mandatory和immediate参数逻辑实现
4. 消息持久化与非持久化部分实现。

## 消息的消费流程

1. 消费的ack机制实现
2. 消费的pull模式实现
3. 消费的push模式实现
4. basicQos逻辑实现

**Comment by gaoran10** [comment]
Use #22 instead of this issue, so I close this issue.
