### ISSUE TITLE
MVP tasks of second stage 0.0.1

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/aop#22]
## Goals
1. Multiple exchange types
2. Multiple Message routers
3. Exchange and queue bind
4. Queue message IDs replication
5. Reading messages from the queue

## Tasks:
1. - [x] Design doc: https://docs.google.com/document/d/1hUU2CacW0218UJQvUEJ-dwrzQ4_Zo0lJnTZ_HhZe1pg/edit?usp=sharing (@codelipenghui)
2. - [x] In-memory implementation (@codelipenghui)(#23)
        - [x] In-memory integration (@gaoran10)(#30)
3. - [x] Persistent exchange message store implementation(write, read)
        - [x] write (@gaoran10)(#32)
        - [x] read (@wangshaojie4039 )(#37 )
4. - [x] Message routers(Direct, Fanout, Topic, Headers)(@zhanghaou )(#38 )
5. - [x] Persistent queue message store implementation(write, read)
        - [x] write (@gaoran10)(#33)
        - [x] read (@wangshaojie4039 )(#37)
6. - [x] Queue message IDs replication(@wangshaojie4039)(#37)
7.  - [ ] Pulsar topic resource binding
8. - [x] Router rule and exchange type metadata persistence(@zhanghaou )
9. - [ ] Vhost creation(Single bundle)(@zhanghaou )
10. - [x] Message ACK / NACK / Reject(@wangshaojie4039)(#37)

## Apache Pulsar related tasks:
1. Topic resource binding
2. Managed ledger properties support(@zhanghaou )

**Comment by sijie** [comment]
Close this task since the second stage is already completed.
